apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-ui
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shark-ui
  template:
    metadata:
      labels:
        app: shark-ui
    spec:
      containers:
      - image: gcr.io/test-oracle-msig/nodejs-shark:latest
        name: shark-ui
        ports:
        - containerPort: 80