apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shark-ui
  template:
    metadata:
      labels:
        app: shark-ui
    spec:
      containers:
      - image: jibon/nodejs-shark-ui:latest
        name: shark-ui
        ports:
        - containerPort: 80