apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shark-ui
  template:
    metadata:
      labels:
        app: shark-ui
    spec:
      containers:
      - image: gcr.io/smartfren-labs/nodejs-shark:latest
        name: shark-ui
        ports:
        - containerPort: 80
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "250m"