apiVersion: apps/v1
kind: Deployment
metadata:
 name: shark-ui
spec:
 replicas: 2
 selector:
   matchLabels:
     app: shark-ui
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: shark-ui
   spec:
     containers:
     - name: shark-ui
       image: asia.gcr.io/smartfren-labs/nodejs-shark/nodejs-shark:latest
       ports:
       - name: http
         containerPort: 80