apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shark-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shark-ui
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50